### PR TITLE
Added sorting of log streams by Descending

### PR DESCRIPTION
**Pull request by bond95**

### CODE REVIEW

**Review by tisnik — APPROVED** [review]
LGTM

**Comment by joselsegura** [comment]
LGTM, does it make any effect on creating the log streams?

**Comment by bond95** [comment]
@joselsegura on creation, no.

**Comment by bond95** [comment]
@joselsegura @tisnik could you, please, merge if everything is alright, because I don't have rights for that.

**Comment by tisnik** [comment]
@bond95 sure!

**Pull request merged**
